"""first

Revision ID: f73da4785ebd
Revises: 
Create Date: 2025-01-18 10:52:49.028087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f73da4785ebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tipo_manutencao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencao_id'), 'manutencao', ['id'], unique=False)
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('vencimento', sa.DateTime(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_id'), 'pagamento', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_veiculo_id'), 'veiculo', ['id'], unique=False)
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrato_id'), 'contrato', ['id'], unique=False)
    op.create_table('veiculomanutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('manutencao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manutencao_id'], ['manutencao.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculomanutencao_id'), 'veiculomanutencao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculomanutencao_id'), table_name='veiculomanutencao')
    op.drop_table('veiculomanutencao')
    op.drop_index(op.f('ix_contrato_id'), table_name='contrato')
    op.drop_table('contrato')
    op.drop_index(op.f('ix_veiculo_id'), table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_pagamento_id'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_index(op.f('ix_manutencao_id'), table_name='manutencao')
    op.drop_table('manutencao')
    # ### end Alembic commands ###
